### ISSUE TITLE
Crashes on 'puppet' keyword

### ISSUE THREAD

**Issue by dzil123** [Scony/godot-gdscript-toolkit#108]
**Affects gdtoolkit version**: 3.2.8

Both gdlint and gdformat crash when encountering a gdscript file with the `puppet` keyword.
[This keyword has been built-in](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html#keywords) to GDScript since Godot 3.1. [`puppet` keyword documentation](https://docs.godotengine.org/en/3.2/tutorials/networking/high_level_multiplayer.html#master-and-puppet-keywords)

**Sample file:**
```
extends Node

puppet var variable = 10
```

**Traceback:**
```
$ gdformat .
exception during formatting of ./Script.gd
Traceback (most recent call last):
  File "/path/to/python/lib/python3.8/site-packages/lark/lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/path/to/python/lib/python3.8/site-packages/lark/lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'v' at line 3 col 8

puppet var variable = 10
       ^

Expecting: {'_NL', 'FUNC'}

Previous tokens: Token(PUPPET, 'puppet')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/python/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/path/to/python/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 156, in main
    raise e
  File "/path/to/python/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 143, in main
    code_parse_tree = parser.parse(code, gather_metadata=True)
  File "/path/to/python/lib/python3.8/site-packages/gdtoolkit/parser/parser.py", line 61, in parse
    self._parser_with_metadata.parse(code)
  File "/path/to/python/lib/python3.8/site-packages/lark/lark.py", line 293, in parse
    return self.parser.parse(text, start=start)
  File "/path/to/python/lib/python3.8/site-packages/lark/parser_frontends.py", line 124, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/path/to/python/lib/python3.8/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/path/to/python/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/path/to/python/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 83, in parse
    for token in stream:
  File "/path/to/python/lib/python3.8/site-packages/lark/indenter.py", line 32, in _process
    for token in stream:
  File "/path/to/python/lib/python3.8/site-packages/lark/lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(TYPE, 'var') at line 3, column 8.
Expected one of: 
        * _NL
        * FUNC
```

**Comment by GuillaumeCailhe** [comment]
I second that, I have the same problem 
Here's a snippet :

```
puppet var puppet_transform:Transform
       ^

Expecting: {'FUNC', '_NL'}

Previous tokens: Token(PUPPET, 'puppet')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 134, in main
    raise e
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 121, in main
    code_parse_tree = parser.parse(code, gather_metadata=True)
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/parser/parser.py", line 61, in parse
    self._parser_with_metadata.parse(code)
  File "/usr/local/lib/python3.9/site-packages/lark/lark.py", line 293, in parse
    return self.parser.parse(text, start=start)
  File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", line 124, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 83, in parse
    for token in stream:
  File "/usr/local/lib/python3.9/site-packages/lark/indenter.py", line 32, in _process
    for token in stream:
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(TYPE, 'var') at line 56, column 8.
Expected one of: 
	* FUNC
	* _NL
```

**Comment by Scony** [comment]
is this `puppet var (...)` construct documented anywhere?

**Comment by Scony** [comment]
Anyway, with Godot 3.3.2 such syntax is illegal. Thus closing.
