### ISSUE TITLE
gdtoolkit doesn't exist

### ISSUE THREAD

**Issue by marko-ljubisavljevic** [Scony/godot-gdscript-toolkit#116]
```
$ pip3 install gdtoolkit
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement gdtoolkit
ERROR: No matching distribution found for gdtoolkit

```

**Comment by Scony** [comment]
what os/env is it? can you install another packages like e.g. `pip3 install docopt`?

**Comment by marko-ljubisavljevic** [comment]
Yes 
```
 $ pip3 install docopt
Defaulting to user installation because normal site-packages is not writeable
Collecting docopt
  Using cached docopt-0.6.2.tar.gz (25 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=19852 sha256=8b0176e2aa5647f46f4527309bae4d3bf587208736d0226ec645556f06092f22
  Stored in directory: /home/ljuba/.cache/pip/wheels/3f/2a/fa/4d7a888e69774d5e6e855d190a8a51b357d77cc05eb1c097c9
Successfully built docopt
Installing collected packages: docopt
Successfully installed docopt-0.6.2

```

**Comment by Scony** [comment]
Could you show me the output of command `pip3 install gdtoolkit --verbose` ?

**Comment by marko-ljubisavljevic** [comment]
```
 $ pip3 install gdtoolkit --verbose
Using pip 21.0.1 from /home/***/.local/lib/python3.6/site-packages/pip (python 3.6)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-3136odgf
Created temporary directory: /tmp/pip-req-tracker-_6qdwv9r
Initialized build tracking at /tmp/pip-req-tracker-_6qdwv9r
Created build tracker: /tmp/pip-req-tracker-_6qdwv9r
Entered build tracker: /tmp/pip-req-tracker-_6qdwv9r
Created temporary directory: /tmp/pip-install-cvfr9luo
1 location(s) to search for versions of gdtoolkit:
* https://pypi.org/simple/gdtoolkit/
Fetching project page and analyzing links: https://pypi.org/simple/gdtoolkit/
Getting page https://pypi.org/simple/gdtoolkit/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/gdtoolkit/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/gdtoolkit/ HTTP/1.1" 304 0
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/12/62/59cc65653707a24e8dc27f19fb757e02c0bff3dab481986fc63e4e206f12/gdtoolkit-3.2.1.tar.gz#sha256=47613d34d366f0bfea0ee14b3450e01ef99c33357db0a93529e60ae1b26930bf (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/cb/68/ecad2a3a97b917f52379ae0ceaa5c746fb0621595c8e10a0f62cd0310fa8/gdtoolkit-3.2.2.tar.gz#sha256=90717d9f1f61768a0415c021edddf96cfad06fc721a9cedaf9f486c0f37b0ee0 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/26/7a/2759b6345ef3a3a89eab872ce061fbb8d66a9bfc41f024211df09ee72641/gdtoolkit-3.2.3.tar.gz#sha256=891acb5d52910446b906c9ef87babfe2f960aafd0db25e3cc5615afecacfc838 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/f9/c7/3b2375f0fe7798dfa38c36990bfd76ad61bd604555641de3d7b52f6439e4/gdtoolkit-3.2.4.tar.gz#sha256=1ec42eec14ec0138f61e0f88bc40f1112e1adfbd54ab7215693d8056354a8052 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/b8/e0/5281538e10c2b6d65f3d4057b41e60f2f2ee2ae90d28b0076077ef6f5e6a/gdtoolkit-3.2.5.tar.gz#sha256=bd00848fd8545bc8628b922967070cded5c0ff64b6ad0040baa69f788451e44e (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/97/41/e3e44a85bcd73409cb4013818b70eec64d36f87cc1ec6360a397665efd38/gdtoolkit-3.2.6.tar.gz#sha256=6694a1347c5da8cab22ac5f3312f1c981e287dbcb00ec135afb269cdec08be5e (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/01/84/09e5cf1958fd99dbb1cd1f7937d112a42e09e48af76f5ea40b1117af1189/gdtoolkit-3.2.7.tar.gz#sha256=63736504a2a61de2fde9d6c7b1a6888c790b7dce0be64eac78c487124376e3e0 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
  Link requires a different Python (3.6.9 not in: '>=3.7'): https://files.pythonhosted.org/packages/25/ca/ae46d183e0943b57e962298ea0055ce2c09443c6d2dcdcf3e919e5763bd5/gdtoolkit-3.2.8.tar.gz#sha256=dfecebd49702b7c1cfc031b48feb6d9f318e86f5266b3faacdb136c06c93f3a3 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7)
Given no hashes to check 0 links for project 'gdtoolkit': discarding no candidates
ERROR: Could not find a version that satisfies the requirement gdtoolkit
ERROR: No matching distribution found for gdtoolkit
Exception information:
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'gdtoolkit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('gdtoolkit')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/***/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('gdtoolkit'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/***/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/***/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/***/.local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for gdtoolkit
Removed build tracker: '/tmp/pip-req-tracker-_6qdwv9r'

```

**Comment by Scony** [comment]
ok - you got python `3.6.9`, which is not supported. `gdtoolkit` requires `python  3.7+`, sorry

**Comment by marko-ljubisavljevic** [comment]
Works :D tnx

**Comment by marko-ljubisavljevic** [comment]
hhahaha works, but I can't open terminal and other programs :D
