### ISSUE TITLE
Array and dict pattern error

### ISSUE THREAD

**Issue by razcore-rad** [Scony/godot-gdscript-toolkit#121]
For this code:

```gdscript
extends Area2D

var is_open := false

var _units := 0

onready var timer: Timer = $Timer


func _ready() -> void:
	match [_units, true]:
		[0, false]: self.is_open = false
		[1, true]: timer.start()
```

I'm getting this following error:

```
❯ gdformat GDFormat.gd                                                                                                                                                18:49:29
exception during formatting of DoorGDFormat.gd
Traceback (most recent call last):
  File "/home/razcore/.local/apps/python/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 134, in main
    raise e
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 123, in main
    formatted_code = format_code(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/formatter.py", line 48, in format_code
    formatted_lines, _ = format_block(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/block.py", line 38, in format_block
    lines, previously_processed_line_number = statement_formatter(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/class_statement.py", line 51, in format_class_statement
    return handlers[statement.data](statement, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/class_statement.py", line 225, in _format_func_statement
    func_lines, last_processed_line_no = format_block(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/block.py", line 38, in format_block
    lines, previously_processed_line_number = statement_formatter(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 27, in format_func_statement
    return handlers[statement.data](statement, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 79, in _format_match_statement
    return _format_branch(prefix, suffix, expr_position, statement, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 109, in _format_branch
    body_lines, last_processed_line_no = format_block(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/block.py", line 38, in format_block
    lines, previously_processed_line_number = statement_formatter(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 27, in format_func_statement
    return handlers[statement.data](statement, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 86, in _format_match_branch
    return _format_branch(prefix, suffix, expr_position, statement, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/function_statement.py", line 99, in _format_branch
    header_lines, last_processed_line_no = format_expression(
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/expression.py", line 24, in format_expression
    _format_standalone_expression(concrete_expression, expression_context, context)[
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/expression.py", line 109, in _format_standalone_expression
    return _format_concrete_expression(expression, expression_context, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/expression.py", line 116, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/expression.py", line 140, in _format_foldable
    single_line_expression = expression_to_str(expression)
  File "/home/razcore/.local/apps/python/lib/python3.8/site-packages/gdtoolkit/formatter/expression_to_str.py", line 22, in expression_to_str
    return {
KeyError: 'array_pattern'
```
Same happens with:

```gdscript
match msg:
	{"index": var index}:
```

Giving the same format of error: `KeyError: 'dict_pattern'`.

**Comment by Scony** [comment]
More complex patterns are not implemented :)

**Comment by razcore-art** [comment]
O, that's a bummer. We could at least skip that section of the code gracefully or something?! Or even the entire file... the problem is it just errors out and I have to go in and run the formatter individually on the files.

**Comment by Scony** [comment]
@razcore-art would the option to keep going despite errors (skipping files with errors) be ok?

**Comment by razcore-art** [comment]
Yeah, I think the usual way to handle these situations is with a warning so the formatting doesn't stop just because of one script might possibly use something that isn't implemented yet.
