### ISSUE TITLE
Linter fails on arg trailing comma

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#206]
```
static func _is_agent_placement_position_valid(position, radius, existing_units, navigation_map_rid,):pass
```

**Comment by njshockey** [comment]
Just had this happen to me. The following code works but it causes an error in gdlint.

```gdscript
func set_turn_order(
	next_turn_order: Array[Enums.MonsterPosition],
	next_move_order: Array[Move],
):
	current_turn_order = next_turn_order
	current_move_order = next_move_order
```

```
Traceback (most recent call last):
  File "/home/nick/.local/bin/gdlint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/__main__.py", line 66, in main
    problems_total += _lint_file(file_path, config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/__main__.py", line 134, in _lint_file
    problems = lint_code(content, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/__init__.py", line 120, in lint_code
    problems += basic_checks.lint(parse_tree, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/basic_checks.py", line 39, in lint
    problems = [problem for cluster in problem_clusters for problem in cluster]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/basic_checks.py", line 39, in <listcomp>
    problems = [problem for cluster in problem_clusters for problem in cluster]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/basic_checks.py", line 37, in <genexpr>
    x[1](parse_tree) if x[0] not in disable else [] for x in checks_to_run_w_tree
    ^^^^^^^^^^^^^^^^
  File "/home/nick/.local/pipx/venvs/gdtoolkit/lib64/python3.11/site-packages/gdtoolkit/linter/basic_checks.py", line 132, in _unused_argument_check
    arg_name = arg_name_token.value  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

Gdlint works again after removing the trailing comma.

```gdscript
func set_turn_order(
	next_turn_order: Array[Enums.MonsterPosition], next_move_order: Array[Move]
):
	current_turn_order = next_turn_order
	current_move_order = next_move_order
```
```
Success: no problems found
```
