### ISSUE TITLE
Accidental use of `not in` ala python causes crash

### ISSUE THREAD

**Issue by tavurth** [Scony/godot-gdscript-toolkit#260]
```gdscript
func _ready() -> void:
    if "hello" not in "hello":
        pass
```

<details>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 590, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 528, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 183, in _format_code
    code_parse_tree = parser.parse(code, gather_metadata=True)
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/parser/parser.py", line 59, in parse
    self._parser_with_metadata.parse(code)
  File "/usr/local/lib/python3.9/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
    raise e
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 183, in parse_from_state
    for token in state.lexer.lex(state):
  File "/usr/local/lib/python3.9/site-packages/lark/indenter.py", line 45, in _process
    for token in stream:
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 599, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/common/exceptions.py", line 14, in lark_unexpected_token_to_str
    return f"{exception.get_context(code)}\n{exception}".strip()
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 142, in <listcomp>
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
AttributeError: 'PatternStr' object has no attribute 'raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 70, in main
    _format_files(files, line_length, safety_checks)
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 145, in _format_files
    success, actually_formatted, formatted_code = _format_code(
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/formatter/__main__.py", line 205, in _format_code
    lark_unexpected_token_to_str(exception, code),
  File "/usr/local/lib/python3.9/site-packages/gdtoolkit/common/exceptions.py", line 16, in lark_unexpected_token_to_str
    return f"{exception}".strip()
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/usr/local/lib/python3.9/site-packages/lark/exceptions.py", line 142, in <listcomp>
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/usr/local/lib/python3.9/site-packages/lark/lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
AttributeError: 'PatternStr' object has no attribute 'raw'
</details>

**Comment by Scony** [comment]
@tavurth what version of gdtoolkit do you use?

**Comment by tavurth** [comment]
@Scony
```sh
▶ gdformat --version
gdformat 4.0.1
```

**Comment by tavurth** [comment]
Aha! Installed the latest version:

```sh
pip3 install "gdtoolkit==4.2.2"
```

And everything working now.
Perhaps we should update the readme or the pip latest version?

In the readme it says:
```
pip3 install "gdtoolkit==4.*"
```

**Comment by Scony** [comment]
@tavurth wasn't `pip3 install "gdtoolkit==4.*"` upgrading the version to the latest one in your case?

**Comment by tavurth** [comment]
@Scony no it didn't, perhaps we should add `--upgrade` there or so

**Comment by Scony** [comment]
@tavurth right, `pip3 install --upgrade "gdtoolkit==4.*"` should do the job. Anyway, I'll put it on the wiki just in case.
