### ISSUE TITLE
gdformat: Multiline Lambda format doesn't works in some cases

### ISSUE THREAD

**Issue by zinclesdown** [Scony/godot-gdscript-toolkit#326]
tested on latest master branch: 9c29fca4656f47d5f572db9cce5fae5a885acb63

It seems that it goes wrong if multiline lambdas are defined directly as param of other functions.

![image](https://github.com/user-attachments/assets/53cdb9eb-6beb-4e07-9b81-84d5a25efcbf)

**Comment by Scony** [comment]
thanks, I'll check that

**Comment by zinclesdown** [comment]
thanks. I've created a new project to reproduce this error.

here's a new script, on a new-created project with godot 4.4 master branch. No any context.
```gdscript
extends Node

func _ready() -> void:
	get_tree().create_timer(1.0).timeout.connect(
		func():
			print("Hello world!")
			print("This is a bug test.")
	)
```

currently i'm using the master branch via pipx.

and here's the following error message of the terminal while i'm using "gdformat bugtest.gd".

```
[zincles@zinarch bug]$ gdformat bugtest.gd
Traceback (most recent call last):
  File "/home/zincles/.local/bin/gdformat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 96, in main
    _format_files(files, line_length, spaces_for_indent, safety_checks)
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 235, in _format_files
    success, actually_formatted, formatted_code = _format_code(
                                                  ^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 289, in _format_code
    check_formatting_safety(
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/formatter/__init__.py", line 33, in check_formatting_safety
    formatted_code_parse_tree = parser.parse(formatted_code, gather_metadata=True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/parser/parser.py", line 54, in parse
    self._parser_with_metadata.parse(adjusted_code)
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/lark/lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/lark/parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/lark/parsers/lalr_parser.py", line 42, in parse
    return self.parser.parse(lexer, start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    return self.parse_from_state(parser_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/lark/parsers/lalr_parser.py", line 100, in parse_from_state
    for token in state.lexer.lex(state):
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/parser/gdscript_indenter.py", line 61, in _process
    yield from self.handle_NL(token)
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/parser/gdscript_indenter.py", line 28, in handle_NL
    for new_token in self._handle_lambdas_on_newline_token_in_parens(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zincles/.local/share/pipx/venvs/gdtoolkit/lib/python3.12/site-packages/gdtoolkit/parser/gdscript_indenter.py", line 108, in _handle_lambdas_on_newline_token_in_parens
    raise DedentError(
lark.indenter.DedentError: Unexpected dedent to column 8. Expected dedent to 4

```

**Comment by zinclesdown** [comment]
Uh... I guess I figured out what's going on here.

It seems to cause problems if functions are chained.

the test case doesn't seem to cover this case. i guess it's better to add another one.
```gdscript
static func foo(x):
	pass

class Class1:
	static func foo(x):
		pass

func _ready() -> void:
	# This is fine,
	foo(
		func():
			print("Hello world")
			print("second line")
	)
	
	# But this cauese issues
	Class1.foo(
		func():
			print('Hello world')
			print("second line")
	)
```

**Comment by Scony** [comment]
Thank you @zinclesdown - the above examples reproduces the problem for me.

The thing is that
```
extends Node

func _ready() -> void:
	get_tree().create_timer(1.0).timeout.connect(
		func():
			print("Hello world!")
			print("This is a bug test.")
	)
```
is being formatted to:
```
extends Node


func _ready() -> void:
	(
		get_tree()
		. create_timer(1.0)
		. timeout
		. connect(
			func():
				print("Hello world!")
				print("This is a bug test.")
		)
	)
```
that to me looks fine and yet breaks lexer when parsed again (for safety checks).

Interestingly Godot 4.3 suffers from the same problem.

The problem with Godot means that I'll need to start fixing this by adding a workaround.

**Comment by Scony** [comment]
Godot bug for reference: https://github.com/godotengine/godot/issues/97204
