### ISSUE TITLE
Exception thrown when using `X is not Y` in gdscript

### ISSUE THREAD

**Issue by dementive** [Scony/godot-gdscript-toolkit#330]
Both the linter and formatter throw a fatal exception when encountering `X is not Y` syntax, which is newer gdscript syntax that was added relatively recently in this pr https://github.com/godotengine/godot/pull/87939.

Here is the simplest example I could make that shows the exception:
```gdscript
extends Control


func _unhandled_input(event: InputEvent) -> void:
	if event is not InputEventKey:
		return

```

When trying to run the linter or formatter on the above script I get these exceptions:

```
Traceback (most recent call last):
  File "python3.12/site-packages/lark/lexer.py", line 590, in lex
    yield lexer.next_token(lexer_state, parser_state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/lexer.py", line 528, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 209, in _format_code
    code_parse_tree = parser.parse(code, gather_metadata=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/gdtoolkit/parser/parser.py", line 62, in parse
    self._parser_with_metadata.parse(adjusted_code)
  File "python3.12/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
    raise e
  File "python3.12/site-packages/lark/parsers/lalr_parser.py", line 183, in parse_from_state
    for token in state.lexer.lex(state):
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/indenter.py", line 45, in _process
    for token in stream:
                 ^^^^^^
  File "python3.12/site-packages/lark/lexer.py", line 599, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.12/site-packages/gdtoolkit/common/exceptions.py", line 14, in lark_unexpected_token_to_str
    return f"{exception.get_context(code)}\n{exception}"
                                            ^^^^^^^^^^^
  File "python3.12/site-packages/lark/exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
                ^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
           ^^^^^^^^^^^^^^^^
AttributeError: 'PatternStr' object has no attribute 'raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "py_env-python3/bin/gdformat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 78, in main
    _format_files(files, line_length, spaces_for_indent, safety_checks)
  File "python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 167, in _format_
files
    success, actually_formatted, formatted_code = _format_code(
                                                  ^^^^^^^^^^^^^
  File "python3.12/site-packages/gdtoolkit/formatter/__main__.py", line 233, in _format_
code
    lark_unexpected_token_to_str(
  File "python3.12/site-packages/gdtoolkit/common/exceptions.py", line 16, in lark_unexp
ected_token_to_str
    return f"{exception}".strip()
             ^^^^^^^^^^^
  File "python3.12/site-packages/lark/exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
                ^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/lark/lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
           ^^^^^^^^^^^^^^^^
AttributeError: 'PatternStr' object has no attribute 'raw'
```

**Comment by Scony** [comment]
@dementive what's you version of gdtoolkit? You can check it with `gdformat --version`

**Comment by dementive** [comment]
Ah I see the problem now, I was using pre-commit and had it pinned to 4.2.2 you're totally right it was my fault using an old version.  Updated to the latest version and it works fine now. Thanks and apologies for any confusion.

**Comment by Scony** [comment]
> Ah I see the problem now, I was using pre-commit and had it pinned to 4.2.2 you're totally right it was my fault using an old version. Updated to the latest version and it works fine now. Thanks and apologies for any confusion.

Thanks for confirming!
