### ISSUE TITLE
gdformat gives assertion error on lambda with direct .call() as variable

### ISSUE THREAD

**Issue by dekaravanhoc** [Scony/godot-gdscript-toolkit#334]
This is the Code:
```
assert(
	(func() -> bool:
		var test_instance: Node = bullet_scene.instantiate()
		var is_needed_class: bool = test_instance is WeaponSystemBullet
		test_instance.free()
		return is_needed_class)
	.call()
)
```
And thats the stack:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "AppData\Roaming\Python\Python310\Scripts\gdformat.exe\__main__.py", line 7, in <module>
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\__main__.py", line 96, in main
    _format_files(files, line_length, spaces_for_indent, safety_checks)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\__main__.py", line 235, in _format_files
    success, actually_formatted, formatted_code = _format_code(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\__main__.py", line 279, in _format_code
    formatted_code = format_code(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\formatter.py", line 61, in format_code
    formatted_lines, _ = format_block(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\block.py", line 55, in format_block
    lines, previously_processed_line_number = statement_formatter(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\class_statement.py", line 46, in format_class_statement
    return handlers[statement.data](statement, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\class_statement.py", line 172, in _format_func_statement
    func_lines, last_processed_line_no = format_block(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\block.py", line 55, in format_block
    lines, previously_processed_line_number = statement_formatter(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\function_statement.py", line 38, in format_func_statement
    return handlers[statement.data](statement, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\function_statement.py", line 46, in _format_expr_statement
    return format_expression(expr, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 28, in format_expression
    _format_standalone_expression(concrete_expression, expression_context, context),
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 46, in _format_standalone_expression
    return _format_concrete_expression(expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 54, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)  # type: ignore
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 90, in _format_foldable
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 381, in _format_call_expression_to_multiple_lines
    return _format_comma_separated_list(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 83, in _format_comma_separated_list
    return _format_concrete_expression(fake_expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 54, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)  # type: ignore
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 90, in _format_foldable
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 525, in _format_comma_separated_list_to_multiple_lines
    formatted_lines += _format_concrete_expression(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 54, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)  # type: ignore
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 90, in _format_foldable
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 549, in _format_contextless_comma_separated_list_to_multiple_lines
    lines = _format_standalone_expression(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 46, in _format_standalone_expression
    return _format_concrete_expression(expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 54, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)  # type: ignore
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 90, in _format_foldable
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 389, in _collapse_getattr_tree_to_dot_chain_and_format_to_multiple_lines
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 723, in _format_dot_chain_to_multiple_lines
    return _format_dot_chain_to_multiple_lines_bottom_up(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 774, in _format_dot_chain_to_multiple_lines_bottom_up
    return _format_concrete_expression(new_actual_expr, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 54, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)  # type: ignore
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 90, in _format_foldable
    return _format_foldable_to_multiple_lines(
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 197, in _format_foldable_to_multiple_lines
    return handlers[expression.data](expression, expression_context, context)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression.py", line 361, in _format_call_expression_to_multiple_lines
    callee = expression_to_str(callee_node)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 31, in expression_to_str
    return {
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 127, in <lambda>
    "non_foldable_dot_chain": lambda e: "".join(map(expression_to_str, e.children)),
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 31, in expression_to_str
    return {
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 77, in <lambda>
    "par_expr": lambda e: f"({standalone_expression_to_str(e.children[0])})",
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 17, in standalone_expression_to_str
    return expression_to_str(expression)
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 31, in expression_to_str
    return {
  File "AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\expression_to_str.py", line 225, in _lambda_to_str
    assert len(a_lambda.children) == 2
AssertionError
```

I am running on the current master.

Thanks!

**Comment by dekaravanhoc** [comment]
Hey, its not the full code. But it is the part that results in the above assert. Removing it and it formats without issue.
Ill check, if I can reproduce it in a full small code example without dependencies.

**Comment by Scony** [comment]
@dekaravanhoc I've managed to reproduce it and fix it. Thanks for reporting!
