### ISSUE TITLE
Missing grammar file

### ISSUE THREAD

**Issue by Awkor** [Scony/godot-gdscript-toolkit#48]
After installing `gdtoolkit` through `pip3`, I tried formatting a script and got the following error:
```
E:\>gdformat Grid.gd
exception during formatting of Grid.gd
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\gdformat-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.1', 'console_scripts', 'gdformat')()
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\formatter\__main__.py", line 102, in main
    raise e
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\formatter\__main__.py", line 95, in main
    gdscript_code=code, max_line_length=line_length
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\formatter\formatter.py", line 13, in format_code
    parse_tree = parser.parse(gdscript_code, gather_metadata=True)
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\parser\parser.py", line 60, in parse
    if gather_metadata
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\parser\parser.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\parser\parser.py", line 82, in _parser_with_metadata
    maybe_placeholders=False,
  File "c:\program files (x86)\python37-32\lib\site-packages\lark\lark.py", line 266, in open
    with open(grammar_filename, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\program files (x86)\\python37-32\\lib\\site-packages\\gdtoolkit\\parser\\gdscript.lark'
```
This happend on Windows 10.

**Comment by Scony** [comment]
Probably `MANIFEST.in` file is broken. I'll fix ASAP. Thanks!

**Comment by Scony** [comment]
@Awkor could you check if `gdtoolkit==3.2.2` is working? I've checked on my Win 10 and should be fie.

`pip install 'gdtoolkit==3.2.2'`

**Comment by Awkor** [comment]
After updating, the error doesn't appear anymore and the program works as intended, thank you.
