### ISSUE TITLE
Linter hangs indefinitely if configuration file is not present

### ISSUE THREAD

**Issue by Awkor** [Scony/godot-gdscript-toolkit#50]
Here's the output after stopping the linter with <kbd>Ctrl</kbd>+<kbd>c</kbd>:
```
E:\>gdlint Grid.gd
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\gdlintrc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\gdlint-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.2', 'console_scripts', 'gdlint')()
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\linter\__main__.py", line 56, in main
    if os.path.isfile(file_path):
  File "c:\program files (x86)\python37-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
KeyboardInterrupt
```
This doesn't happen if there's a configuration file in directory where `gdlint` is executed.

Here's the same output as above plus the configuration file generation:
```
E:\>gdlint Grid.gd
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\gdlintrc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\gdlint-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.2', 'console_scripts', 'gdlint')()
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\linter\__main__.py", line 56, in main
    if os.path.isfile(file_path):
  File "c:\program files (x86)\python37-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
KeyboardInterrupt

E:\>gdlint -d

E:\>gdlint Grid.gd
Grid.gd:2: Error: Definition out of order in global scope (class-definitions-order)
Grid.gd:14: Error: Definition out of order in global scope (class-definitions-order)
Grid.gd:17: Error: Definition out of order in global scope (class-definitions-order)
Grid.gd:18: Error: Definition out of order in global scope (class-definitions-order)
Grid.gd:31: Error: unused function argument 'delta' (unused-argument)

E:\>
```

**Comment by Scony** [comment]
Yeah `while search_dir != Path("/"):` is working on Linux only... I'll change to platform-independent `while search_dir != Path(os.path.abspath(os.sep)):` and it should be fine. Will release soon, thanks!
