### ISSUE TITLE
Installation error : 'No matching distribution found for gdtoolkit'

### ISSUE THREAD

**Issue by ChrisMGeo** [Scony/godot-gdscript-toolkit#66]
Hi I'm trying to install the gdtoolkit from pip, however, I'm getting the following errors:
On typing `pip3 install gdtoolkit`
```
Collecting gdtoolkit
  Could not find a version that satisfies the requirement gdtoolkit (from versions: )
No matching distribution found for gdtoolkit
```
On typing `pip3 install gdtoolkit -vvv`
```
Collecting gdtoolkit
  1 location(s) to search for versions of gdtoolkit:
  * https://pypi.python.org/simple/gdtoolkit/
  Getting page https://pypi.python.org/simple/gdtoolkit/
  Looking up "https://pypi.python.org/simple/gdtoolkit/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/gdtoolkit/" in the cache
  Current age based on date: 155
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 155
  Analyzing links from page https://pypi.org/simple/gdtoolkit/
    The package https://files.pythonhosted.org/packages/12/62/59cc65653707a24e8dc27f19fb757e02c0bff3dab481986fc63e4e206f12/gdtoolkit-3.2.1.tar.gz#sha256=47613d34d366f0bfea0ee14b3450e01ef99c33357db0a93529e60ae1b26930bf (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
    The package https://files.pythonhosted.org/packages/cb/68/ecad2a3a97b917f52379ae0ceaa5c746fb0621595c8e10a0f62cd0310fa8/gdtoolkit-3.2.2.tar.gz#sha256=90717d9f1f61768a0415c021edddf96cfad06fc721a9cedaf9f486c0f37b0ee0 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
    The package https://files.pythonhosted.org/packages/26/7a/2759b6345ef3a3a89eab872ce061fbb8d66a9bfc41f024211df09ee72641/gdtoolkit-3.2.3.tar.gz#sha256=891acb5d52910446b906c9ef87babfe2f960aafd0db25e3cc5615afecacfc838 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
    The package https://files.pythonhosted.org/packages/f9/c7/3b2375f0fe7798dfa38c36990bfd76ad61bd604555641de3d7b52f6439e4/gdtoolkit-3.2.4.tar.gz#sha256=1ec42eec14ec0138f61e0f88bc40f1112e1adfbd54ab7215693d8056354a8052 (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
    The package https://files.pythonhosted.org/packages/b8/e0/5281538e10c2b6d65f3d4057b41e60f2f2ee2ae90d28b0076077ef6f5e6a/gdtoolkit-3.2.5.tar.gz#sha256=bd00848fd8545bc8628b922967070cded5c0ff64b6ad0040baa69f788451e44e (from https://pypi.org/simple/gdtoolkit/) (requires-python:>=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
  Could not find a version that satisfies the requirement gdtoolkit (from versions: )
Cleaning up...
No matching distribution found for gdtoolkit
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for gdtoolkit
```
Is there something else I should be doing in order to fix this.
Any help on why this is happening is appreciated. Thanks!

**Comment by NathanLovato** [comment]
Can you type `pip3 --version`? You should be running from Python 3.7 or 3.8. 3.7 is the minimum required version.

In case you have multiple versions of python installed, you can run e.g. `python3.7 -m pip install gdtoolkit`, installing gdtoolkit through that version of python specifically.

**Comment by ChrisMGeo** [comment]
OK, so my pip3 version was python 3.6, so I used my python 3.8 to install the gdtoolkit, and it worked!!! Thank you so much, and sorry for any trouble.
