### ISSUE TITLE
3 breaking issues: "as Type", multi-type match, and missing commas in enums

### ISSUE THREAD

**Issue by x2f** [Scony/godot-gdscript-toolkit#68]
Here is a list of issues on my code base, with gdformat version 2.6.

Besides these issues, everything else seems to work fine (thanks for writing gdformat :-)

## (1) Support for "as Type"

```
	texture = Sys.Cache.resource("res://resources/%s.jpg" % [val]) as Texture)
```
  
becomes...

```
  texture = (
		Sys.Cache.resource("res://resources/%s.jpg" % [val])
		as Texture
	)
```

Godot does not support "as Texture" on a different line. So the code modified by gdformat fails to run.

Should be:

```
  texture = (
		Sys.Cache.resource("res://resources/%s.jpg" % [val]) as Texture
	)
```

## (2) Support for multi-value match

Something like this:

```
match var:
  1, 2:
    action()
```

... crashes gdformat like this:

```
exception during formatting of test.gd
Traceback (most recent call last):
  File "D:\anaconda3\Scripts\gdformat-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.6', 'console_scripts', 'gdformat')()
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\__main__.py", line 134, in main
    raise e
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\__main__.py", line 127, in main
    comment_parse_tree=comment_parse_tree,
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\formatter.py", line 52, in format_code
    GLOBAL_SCOPE_SURROUNDING_EMPTY_LINES_TABLE,
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\block.py", line 39, in format_block
    statement, context
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\class_statement.py", line 51, in format_class_statement
    return handlers[statement.data](statement, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\class_statement.py", line 228, in _format_func_statement
    context.create_child_context(last_processed_line_no),
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\block.py", line 39, in format_block
    statement, context
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 27, in format_func_statement
    return handlers[statement.data](statement, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 79, in _format_match_statement
    return _format_branch(prefix, suffix, expr_position, statement, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 112, in _format_branch
    context.create_child_context(last_processed_line_no),
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\block.py", line 39, in format_block
    statement, context
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 27, in format_func_statement
    return handlers[statement.data](statement, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 86, in _format_match_branch
    return _format_branch(prefix, suffix, expr_position, statement, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\function_statement.py", line 100, in _format_branch
    expr, expression_context, context
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\expression.py", line 24, in format_expression
    _format_standalone_expression(concrete_expression, expression_context, context)[
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\expression.py", line 109, in _format_standalone_expression
    return _format_concrete_expression(expression, expression_context, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\expression.py", line 116, in _format_concrete_expression
    return _format_foldable(expression, expression_context, context)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\expression.py", line 140, in _format_foldable
    single_line_expression = expression_to_str(expression)
  File "d:\anaconda3\lib\site-packages\gdtoolkit-3.2.6-py3.7.egg\gdtoolkit\formatter\expression_to_str.py", line 79, in expression_to_str
    }[expression.data](expression)
KeyError: 'list_pattern'
```

## (3) Missing comma in an enum crashes gdformat.

This enum:

```
enum PlayerControlMode {
	PCM_NORMAL
	PCM_ALWAYS_DOUBLE_CLICK,
	PCM_ALWAYS_SINGLE_CLICK
}
```

... led to this exception:

```
File "d:\anaconda3\lib\site-packages\lark\lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(TYPE, 'PCM_ALWAYS_DOUBLE_CLICK') at line 26, column 2.
Expected one of:
        * COMMA
        * _NL
        * EQUAL
        * RBRACE
        
```

**Comment by Scony** [comment]
Thanks for reporting!

1) looks like a godot bug, but anyway I must fix formatter so it produces a working code
2) this is actually not implemented but I will do it soon (#46)
3) gdtoolkit does not have exception handling implemented yet, hence such an ugly error :) it is to be implemented as well (#2)

**Comment by p-brighenti** [comment]
Running into the first issue reported here while using the VSCode extension as well. It's a shame if it's actually a problem with GDScript as some types have very long (and descriptive) names which makes this wrapping very welcome for code readability.

**Comment by Scony** [comment]
True. Anyway, I've encouraged vnen to use gdtoolkit's test suite before he introduces GDScript 4.0, so hopefully, we can get rid of those problems :)

**Comment by Scony** [comment]
1) will be soon delivered
2) merged already
3) will come as #2
