### ISSUE TITLE
Exception(s) when parsing file

### ISSUE THREAD

**Issue by qarmin** [Scony/godot-gdscript-toolkit#83]
This file probably should expose a lot of problems with parser/formatter - https://github.com/qarmin/The-worst-Godot-test-project/blob/master/MainScenes/Operators.gd

Exception:
```
exception during formatting of ./MainScripts/Operators.gd
Traceback (most recent call last):
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'b' at line 76 col 4

		0b101010101010101010101
   ^

Expecting: {'PLUS', 'MINUS', 'IF', 'RSQB', '__ANON_12', '__ANON_4', 'SEMICOLON', 'LESSTHAN', '__ANON_11', 'ELSE', 'OR', 'LSQB', 'COMMA', '__ANON_15', 'DOT', '__ANON_14', 'SETGET', '__ANON_13', 'EQUAL', 'IS', '__ANON_10', 'VBAR', '__ANON_17', '__ANON_18', '__ANON_19', '__ANON_5', '__ANON_7', '__ANON_16', '__ANON_2', 'RBRACE', 'RPAR', '__ANON_3', '_NL', 'COLON', '__ANON_9', 'STAR', 'CIRCUMFLEX', 'SLASH', 'IN', 'MORETHAN', 'PERCENT', '__ANON_20', '__ANON_8', 'AND', 'AMPERSAND', 'AS'}

Previous tokens: Token(NUMBER, '0')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rafal/.local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 134, in main
    raise e
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 121, in main
    code_parse_tree = parser.parse(code, gather_metadata=True)
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/parser/parser.py", line 61, in parse
    self._parser_with_metadata.parse(code)
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/lark.py", line 293, in parse
    return self.parser.parse(text, start=start)
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 124, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 83, in parse
    for token in stream:
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/indenter.py", line 32, in _process
    for token in stream:
  File "/home/rafal/.local/lib/python3.8/site-packages/lark/lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(TYPE, 'b101010101010101010101') at line 76, column 4.
Expected one of: 
	* PLUS
	* MINUS
	* IF
	* RSQB
	* __ANON_12
	* __ANON_4
	* SEMICOLON
	* LESSTHAN
	* __ANON_11
	* ELSE
	* OR
	* LSQB
	* COMMA
	* __ANON_15
	* DOT
	* __ANON_14
	* SETGET
	* __ANON_13
	* EQUAL
	* IS
	* __ANON_10
	* VBAR
	* __ANON_17
	* __ANON_18
	* __ANON_19
	* __ANON_5
	* __ANON_7
	* __ANON_16
	* __ANON_2
	* RBRACE
	* RPAR
	* __ANON_3
	* _NL
	* COLON
	* __ANON_9
	* STAR
	* CIRCUMFLEX
	* SLASH
	* IN
	* MORETHAN
	* PERCENT
	* __ANON_20
	* __ANON_8
	* AND
	* AMPERSAND
	* AS
```

**Comment by ModProg** [comment]
This should be fixed as of #103, at least the error in the log and link seams to be dead.
