### ISSUE TITLE
Exception gdtoolkit.formatter.safety_checks.CommentPersistenceViolation

### ISSUE THREAD

**Issue by qarmin** [Scony/godot-gdscript-toolkit#84]
File which caused error - https://github.com/qarmin/The-worst-Godot-test-project/blob/d5d5a5cb28dfe070848ce88fdfe0b89985d294ac/Autoloads/Autoload.gd

Exception
```
exception during formatting of ./Autoloads/Autoload.gd
Traceback (most recent call last):
  File "/home/rafal/.local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 149, in main
    raise e
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 137, in main
    check_formatting_safety(
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__init__.py", line 26, in check_formatting_safety
    check_comment_persistence(
  File "/home/rafal/.local/lib/python3.8/site-packages/gdtoolkit/formatter/safety_checks.py", line 86, in check_comment_persistence
    raise CommentPersistenceViolation
gdtoolkit.formatter.safety_checks.CommentPersistenceViolation
```

**Comment by Scony** [comment]
it's because you have comments inside of a dictionary (expression) and that's going to be implemented in #30
