### ISSUE TITLE
Various errors with gdtoolkit 3.2.8 

### ISSUE THREAD

**Issue by NathanLovato** [Scony/godot-gdscript-toolkit#98]
The new update is failing to format scripts on all projects where I tested it. I'm getting mainly two errors:

1. CommentPersistenceViolation
2. Parser error.

You can find two scripts triggering these errors along with the tracebacks below: [gdtoolkit-3.2.8-error-scripts.zip](https://github.com/Scony/godot-gdscript-toolkit/files/5229336/gdtoolkit-3.2.8-error-scripts.zip)

## CommentPersistenceViolation

Happens on many files with comments. See attached ObjectRegistry.gd.

```sh
exception during formatting of /home/gdquest/Repositories/godot-2d-space-game/project/Autoload/ObjectRegistry.gd
Traceback (most recent call last):
  File "/home/gdquest/.local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 171, in main
    raise e
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 159, in main
    check_formatting_safety(
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__init__.py", line 26, in check_formatting_safety
    check_comment_persistence(
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/safety_checks.py", line 93, in check_comment_persistence
    raise CommentPersistenceViolation
gdtoolkit.formatter.safety_checks.CommentPersistenceViolation
```

## Parser error

See attached file BattlerAI.gd

```sh
exception during formatting of /home/gdquest/Repositories/godot-2d-jrpg-combat/godot/CombatSystem/Battler/AI/BattlerAI.gd
Traceback (most recent call last):
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 61, in get_action
    return states[state][token.type]
KeyError: 'COMMA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gdquest/.local/bin/gdformat", line 8, in <module>
    sys.exit(main())
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 156, in main
    raise e
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/formatter/__main__.py", line 143, in main
    code_parse_tree = parser.parse(code, gather_metadata=True)
  File "/home/gdquest/.local/lib/python3.8/site-packages/gdtoolkit/parser/parser.py", line 61, in parse
    self._parser_with_metadata.parse(code)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/lark.py", line 293, in parse
    return self.parser.parse(text, start=start)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 124, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 85, in parse
    action, arg = get_action(token)
  File "/home/gdquest/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 64, in get_action
    raise UnexpectedToken(token, expected, state=state)
lark.exceptions.UnexpectedToken: Unexpected token Token(COMMA, ',') at line 36, column 25.
Expected one of: 
	* RPAR
```

**Comment by Scony** [comment]
Thanks, I'll try to fix it after work. For now, I've yanked `3.2.8`.

**Comment by lihop** [comment]
Here's a minimal script to reproduce the Parser error:
```gdscript
func test():
	assert(true, "some message")
```
The parser doesn't like assert being called with the message argument.
It seems to be related to this patch: https://github.com/Scony/godot-gdscript-toolkit/commit/604b67f11a5cc6095bcd38a516350153bad401d5.
