### ISSUE TITLE
Exception when parsing an empty, but valid, class

### ISSUE THREAD

**Issue by wooky** [Scony/godot-gdscript-toolkit#99]
For a file with the contents
```
class Empty:
    pass
```
an exception is being thrown:
```
Traceback (most recent call last):
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'p' at line 2 col 5

    pass
    ^

Expecting: {'EXTENDS', 'STATIC', 'MASTER', 'PUPPET', 'ONREADY', 'FUNC', 'TOOL', 'ENUM', 'REGULAR_STRING', '__ANON_0', 'CLASS', 'EXPORT', 'CONST', 'REMOTE', '_NL', 'REMOTESYNC', 'SYNC', 'SIGNAL', 'VAR', 'LONG_STRING'}

Previous tokens: Token(_NL, '\n    ')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yakov\AppData\Local\Programs\Python\Python37-32\Scripts\gdlint-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.7', 'console_scripts', 'gdlint')()
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\gdtoolkit\linter\__main__.py", line 88, in main
    problems = lint_code(content, config)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\gdtoolkit\linter\__init__.py", line 102, in lint_code
    parse_tree = parser.parse(gdscript_code, gather_metadata=True)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\gdtoolkit\parser\parser.py", line 62, in parse
    if gather_metadata
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\lark.py", line 293, in parse
    return self.parser.parse(text, start=start)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\parser_frontends.py", line 124, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\parsers\lalr_parser.py", line 83, in parse
    for token in stream:
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\indenter.py", line 32, in _process
    for token in stream:
  File "c:\users\yakov\appdata\local\programs\python\python37-32\lib\site-packages\lark\lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(TYPE, 'pass') at line 2, column 5.
Expected one of:
        * EXTENDS
        * STATIC
        * MASTER
        * PUPPET
        * ONREADY
        * FUNC
        * TOOL
        * ENUM
        * REGULAR_STRING
        * CLASS
        * EXPORT
        * CONST
        * REMOTE
        * _NL
        * REMOTESYNC
        * SYNC
        * SIGNAL
        * VAR
        * LONG_STRING
```

**Comment by Scony** [comment]
what is the Godot version? do you know since which version such a syntax is supported?

**Comment by wooky** [comment]
I'm using the latest 3.2.3 version, and it's a valid block of code. I don't know when that syntax was originally introduced.
